#!/bin/sh -eu

. $(dirname $0)/../core/setup.sh

banner Authenticate request
#--------------------------

authed_request=$(mktemp -p dist zodiac_cli_test_XXXXXX)
trap "rm -rf ${authed_request}" EXIT

export TSRP_KEY_ID="DWPXY16451eb6f287b4d6b46ec13e36607653b"
export TSRP_SECRET_KEY="LWTGZD89cf43bed574d6e6a54bf436b3a4ba8dc658973b85aa5bfc80f05e38e01d28d7"

cat test/data/unix-request | $TSRP authenticate -u -e 60 > $authed_request

banner Verify request
#--------------------

cat $authed_request | $TSRP verify
