#!/bin/sh -eu

. $(dirname $0)/../core/setup.sh

banner TSRP Display Version
#--------------------------

$TSRP -v | grep -q tsrp

$TSRP --version

banner TSRP Display Help
#-----------------------

$TSRP -h

$TSRP --help

TSRP="$TSRP --dry-run"

$TSRP authenticate

$TSRP authenticate -e 60

$TSRP verify

banner REQTOOL Display Version
#--------------------------

$REQTOOL -v | grep -q reqtool

$REQTOOL --version

banner REQTOOL Display Help
#-----------------------

$REQTOOL -h

$REQTOOL --help

REQTOOL="$REQTOOL --dry-run"

$REQTOOL canonise

$REQTOOL canonise -u

