#!/bin/sh -eu

. $(dirname $0)/../core/setup.sh

banner TSRP Display Version
#--------------------------

$TSRP -v | grep -q tsrp

$TSRP --version

banner TSRP Display Help
#-----------------------

$TSRP -h

$TSRP --help

$TSRP debug -h

$TSRP debug --help

TSRP="$TSRP --dry-run"

$TSRP authenticate

$TSRP authenticate -e 60

$TSRP verify

$TSRP debug auth-string

$TSRP debug auth-string -e 100

$TSRP debug auth-string -u -e 100

$TSRP debug canonise

$TSRP debug canonise -u

